# Generated by Django 2.2.1 on 2019-07-05 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_kcal', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total_carbohydrates_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('dietary_fiber_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('starch_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('sugars_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total_fat_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('saturated_fat_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('monounsaturated_fat_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('polyunsaturated_fat_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total_trans_fatty_acids_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total_omega_3_fatty_acids_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total_omega_6_fatty_acids_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('vitamin_a_iu', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('vitamin_c_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('vitamin_d_iu', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('vitamin_e_alpha_tocopherol_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('vitamin_k_mcg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('thiamin_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('riboflavin_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('niacin_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('vitamin_b6_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('folate_mcg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('vitamin_b12_mcg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('pantothenic_acid_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('choline_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('betaine_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('calcium_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('iron_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('magnesium_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('phosphorus_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('potassium_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('zinc_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('copper_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('manganese_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('selenium_mcg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('fluoride_mcg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('cholesterol_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('phytosterols', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('alcohol_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('water_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('ash_g', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('caffeine_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('theobromine_mg', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('reference_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('amount_in_package', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('where_to_buy', models.CharField(blank=True, max_length=100, null=True)),
                ('source_nutritional_information', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
