# Generated by Django 2.2.1 on 2019-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calories', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fat', models.DecimalField(decimal_places=6, max_digits=20)),
                ('protein', models.DecimalField(decimal_places=6, max_digits=20)),
                ('carbohydrates', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
        ),
    ]
