# Generated by Django 2.2.1 on 2019-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuredfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
