# Generated by Django 2.2.1 on 2019-06-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measuredfood', '0002_auto_20190610_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawingredient',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawingredient',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawingredient',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawingredient',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
